### ISSUE TITLE
improve layout / design of instruction labels

### ISSUE THREAD

**Issue by thestinger** [copperhead/Attestation#18]
At the moment, they get screwed up in landscape mode. The QR code should probably be moved all the way to the right side or the left side so there's room to have the label. At the moment, the image view / bitmap ends up on top of the text view so it can overlap.

**Comment by chirayudesai** [comment]
I did https://github.com/chirayudesai/Attestation/commit/edcaa73ab683884feb32f4fd916cb3c23c8e1957 - this still uses the hardcoded margins (#20) but should do the job for now.

**Comment by thestinger** [comment]
@chirayudesai It can still overlap in portrait mode though. It happens on my Nexus 9.

**Comment by thestinger** [comment]
This is resolved.
