### ISSUE TITLE
improve button layout

### ISSUE THREAD

**Issue by thestinger** [copperhead/Attestation#20]
It currently uses offsets from the top and bottom which is strange.

**Comment by chirayudesai** [comment]
Not sure of a better solution yet, but I have https://github.com/chirayudesai/Attestation/commit/a22a89a37ec2d07d27998b1c67720cededefca29 for now.

**Comment by thestinger** [comment]
I'll close this for now. Nicer design would be good but it's not clear what it should do yet.

**Comment by thestinger** [comment]
@chirayudesai Try using split screen and resizing the screen. The 2nd button should probably just be replaced below the 1st button with some padding between them.

**Comment by thestinger** [comment]
This is resolved.
