### ISSUE TITLE
provide some initial instructions on the starting screen

### ISSUE THREAD

**Issue by thestinger** [copperhead/Attestation#21]

**Comment by chirayudesai** [comment]
So I had two ideas about this:

1. Add text above each button with some info on what it does (easy, literally just add two textviews above the button and hide them when hiding the button)
2. Add some sort of a welcome screen, unsure how much effort would that require.

**Comment by thestinger** [comment]
I'd rather have it on the same screen.

**Comment by thestinger** [comment]
It could also just be a help option providing instructions.

**Comment by thestinger** [comment]
Going to skip this for now because I'm not quite sure what kind of instructions I want to have there. A welcome screen might make more sense but I don't want to worry about that right now.

**Comment by thestinger** [comment]
This is implemented.
